import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const users = [
  {
    id: 19,
    email: "cameronziny@gmail.com",
    name: "divox",
    accountId: null,
    clerkUserId: "user_2XJ2G6uNp3SZazCERjN0HJEdlGa",
  },
  {
    id: 20,
    email: "test@test.com",
    name: "bob",
    accountId: null,
    clerkUserId: "user_123",
  },
];

const userCharacters = [
  {
    characterId: 39,
    clerkUserId: "user_123",
  },
  {
    characterId: 14,
    clerkUserId: "user_2XJ2G6uNp3SZazCERjN0HJEdlGa",
  },
  {
    characterId: 15,
    clerkUserId: "user_2XJ2G6uNp3SZazCERjN0HJEdlGa",
  },
  {
    characterId: 16,
    clerkUserId: "user_2XJ2G6uNp3SZazCERjN0HJEdlGa",
  },
  {
    characterId: 17,
    clerkUserId: "user_2XJ2G6uNp3SZazCERjN0HJEdlGa",
  },
  {
    characterId: 18,
    clerkUserId: "user_2XJ2G6uNp3SZazCERjN0HJEdlGa",
  },
  {
    characterId: 19,
    clerkUserId: "user_2XJ2G6uNp3SZazCERjN0HJEdlGa",
  },
];

const charactersSet1 = [
  {
    id: 39,
    webId: "nWPUlz1kqEU",
    deathsLastWeek: 0,
    realmPointsLastWeek: 0,
    soloKillsLastWeek: 0,
    totalDeaths: 28952,
    totalRealmPoints: 418893210,
    totalSoloKills: 375,
    lastUpdated: new Date("2023-12-24T01:21:07.028Z"),
    characterName: "Herorius",
    previousCharacterName: null,
    className: "Hero",
    nameLastUpdated: new Date("2023-12-18T05:00:00.000Z"),
    realm: "Hibernia",
    heraldAlbionDeathBlows: 62462,
    heraldAlbionDeaths: 0,
    heraldAlbionKills: 579162,
    heraldAlbionSoloKills: 152,
    heraldBountyPoints: 497639,
    heraldCharacterWebId: "nWPUlz1kqEU",
    heraldClassName: "Hero",
    heraldGuildName: "I Hueter des Waldes I",
    heraldLevel: 50,
    heraldMasterLevel: "10 Battlemaster",
    heraldMidgardDeathBlows: 74482,
    heraldMidgardDeaths: 0,
    heraldMidgardKills: 728142,
    heraldMidgardSoloKills: 224,
    heraldName: "Herorius FistoftheNorthStar",
    heraldRace: "Graoch",
    heraldRealm: 3,
    heraldRealmPoints: 433745804,
    heraldServerName: "Ywain2",
    heraldTotalDeathBlows: 136944,
    heraldTotalDeaths: 29252,
    heraldTotalKills: 1307304,
    heraldTotalSoloKills: 376,
    heraldHiberniaDeathBlows: null,
    heraldHiberniaDeaths: null,
    heraldHiberniaKills: null,
    heraldHiberniaSoloKills: null,
  },
];

const charactersSet2 = [
  {
    id: 14,
    webId: "gsXgHV4WYqM",
    deathsLastWeek: 0,
    realmPointsLastWeek: 0,
    soloKillsLastWeek: 0,
    totalDeaths: 83,
    totalRealmPoints: 726524,
    totalSoloKills: 0,
    lastUpdated: new Date("2023-12-24T00:50:59.605Z"),
    characterName: "Divoxybo",
    previousCharacterName: "Unknown",
    className: "Bonedancer",
    nameLastUpdated: new Date("2023-12-21T14:52:13.991Z"),
    realm: "Midgard",
    heraldAlbionDeathBlows: 79,
    heraldAlbionDeaths: 0,
    heraldAlbionKills: 1013,
    heraldAlbionSoloKills: 0,
    heraldBountyPoints: 1250,
    heraldCharacterWebId: "gsXgHV4WYqM",
    heraldClassName: "Bonedancer",
    heraldGuildName: "Pygmalion Effect",
    heraldLevel: 50,
    heraldMasterLevel: "10 Convoker",
    heraldMidgardDeathBlows: null,
    heraldMidgardDeaths: null,
    heraldMidgardKills: null,
    heraldMidgardSoloKills: null,
    heraldName: "Divoxybo",
    heraldRace: "Kobold",
    heraldRealm: 2,
    heraldRealmPoints: 726524,
    heraldServerName: "Ywain5",
    heraldTotalDeathBlows: 105,
    heraldTotalDeaths: 83,
    heraldTotalKills: 1466,
    heraldTotalSoloKills: 0,
    heraldHiberniaDeathBlows: 26,
    heraldHiberniaDeaths: 0,
    heraldHiberniaKills: 453,
    heraldHiberniaSoloKills: 0,
  },
  {
    id: 15,
    webId: "LDc8uFw-FRw",
    deathsLastWeek: 0,
    realmPointsLastWeek: 0,
    soloKillsLastWeek: 0,
    totalDeaths: 207,
    totalRealmPoints: 1185688,
    totalSoloKills: 0,
    lastUpdated: new Date("2023-12-24T00:50:59.638Z"),
    characterName: "Divoxye",
    previousCharacterName: "Unknown",
    className: "Healer",
    nameLastUpdated: new Date("2023-12-21T14:52:14.018Z"),
    realm: "Midgard",
    heraldAlbionDeathBlows: 0,
    heraldAlbionDeaths: 0,
    heraldAlbionKills: 1194,
    heraldAlbionSoloKills: 0,
    heraldBountyPoints: 133139,
    heraldCharacterWebId: "LDc8uFw-FRw",
    heraldClassName: "Healer",
    heraldGuildName: "Dark Dawn",
    heraldLevel: 50,
    heraldMasterLevel: "10 Perfecter",
    heraldMidgardDeathBlows: null,
    heraldMidgardDeaths: null,
    heraldMidgardKills: null,
    heraldMidgardSoloKills: null,
    heraldName: "Divoxye",
    heraldRace: "Frostalf",
    heraldRealm: 2,
    heraldRealmPoints: 1185688,
    heraldServerName: "Ywain7",
    heraldTotalDeathBlows: 0,
    heraldTotalDeaths: 207,
    heraldTotalKills: 2799,
    heraldTotalSoloKills: 0,
    heraldHiberniaDeathBlows: 0,
    heraldHiberniaDeaths: 0,
    heraldHiberniaKills: 1605,
    heraldHiberniaSoloKills: 0,
  },
  {
    id: 16,
    webId: "Rzs1GmV8EqU",
    deathsLastWeek: 0,
    realmPointsLastWeek: 0,
    soloKillsLastWeek: 0,
    totalDeaths: 49,
    totalRealmPoints: 600686,
    totalSoloKills: 0,
    lastUpdated: new Date("2023-12-24T00:50:59.667Z"),
    characterName: "Divoxylalah",
    previousCharacterName: "Unknown",
    className: "Mauler",
    nameLastUpdated: new Date("2023-12-21T14:52:14.044Z"),
    realm: "Hibernia",
    heraldAlbionDeathBlows: 41,
    heraldAlbionDeaths: 0,
    heraldAlbionKills: 220,
    heraldAlbionSoloKills: 0,
    heraldBountyPoints: 136213,
    heraldCharacterWebId: "Rzs1GmV8EqU",
    heraldClassName: "Mauler",
    heraldGuildName: "Pogue Mahone",
    heraldLevel: 50,
    heraldMasterLevel: "10 Battlemaster",
    heraldMidgardDeathBlows: 50,
    heraldMidgardDeaths: 0,
    heraldMidgardKills: 284,
    heraldMidgardSoloKills: 0,
    heraldName: "Divoxylalah",
    heraldRace: "Firbolg",
    heraldRealm: 3,
    heraldRealmPoints: 600686,
    heraldServerName: "Ywain5",
    heraldTotalDeathBlows: 91,
    heraldTotalDeaths: 49,
    heraldTotalKills: 504,
    heraldTotalSoloKills: 0,
    heraldHiberniaDeathBlows: null,
    heraldHiberniaDeaths: null,
    heraldHiberniaKills: null,
    heraldHiberniaSoloKills: null,
  },
  {
    id: 17,
    webId: "GLhEGymUwNE",
    deathsLastWeek: 0,
    realmPointsLastWeek: 0,
    soloKillsLastWeek: 0,
    totalDeaths: 30,
    totalRealmPoints: 4472654,
    totalSoloKills: 0,
    lastUpdated: new Date("2023-12-24T00:50:59.702Z"),
    characterName: "Divoxylapantera",
    previousCharacterName: "Unknown",
    className: "Druid",
    nameLastUpdated: new Date("2023-12-21T14:52:14.07Z"),
    realm: "Hibernia",
    heraldAlbionDeathBlows: 6,
    heraldAlbionDeaths: 0,
    heraldAlbionKills: 775,
    heraldAlbionSoloKills: 0,
    heraldBountyPoints: 124689,
    heraldCharacterWebId: "GLhEGymUwNE",
    heraldClassName: "Druid",
    heraldGuildName: "Irish Sea Guy",
    heraldLevel: 50,
    heraldMasterLevel: "10 Perfecter",
    heraldMidgardDeathBlows: 12,
    heraldMidgardDeaths: 0,
    heraldMidgardKills: 1220,
    heraldMidgardSoloKills: 0,
    heraldName: "Divoxylapantera",
    heraldRace: "Celt",
    heraldRealm: 3,
    heraldRealmPoints: 4472654,
    heraldServerName: "Ywain5",
    heraldTotalDeathBlows: 18,
    heraldTotalDeaths: 30,
    heraldTotalKills: 1995,
    heraldTotalSoloKills: 0,
    heraldHiberniaDeathBlows: null,
    heraldHiberniaDeaths: null,
    heraldHiberniaKills: null,
    heraldHiberniaSoloKills: null,
  },
  {
    id: 18,
    webId: "zLms6CeUXoI",
    deathsLastWeek: 0,
    realmPointsLastWeek: 0,
    soloKillsLastWeek: 0,
    totalDeaths: 103,
    totalRealmPoints: 420416,
    totalSoloKills: 8,
    lastUpdated: new Date("2023-12-24T00:50:59.729Z"),
    characterName: "Divoxylavache",
    previousCharacterName: "Unknown",
    className: "Reaver",
    nameLastUpdated: new Date("2023-12-21T14:52:14.096Z"),
    realm: "Albion",
    heraldAlbionDeathBlows: null,
    heraldAlbionDeaths: null,
    heraldAlbionKills: null,
    heraldAlbionSoloKills: null,
    heraldBountyPoints: 23539,
    heraldCharacterWebId: "zLms6CeUXoI",
    heraldClassName: "Reaver",
    heraldGuildName: "Blaze Away",
    heraldLevel: 50,
    heraldMasterLevel: "10 Banelord",
    heraldMidgardDeathBlows: 62,
    heraldMidgardDeaths: 0,
    heraldMidgardKills: 429,
    heraldMidgardSoloKills: 4,
    heraldName: "Divoxylavache",
    heraldRace: "Korazh",
    heraldRealm: 1,
    heraldRealmPoints: 420416,
    heraldServerName: "Ywain1",
    heraldTotalDeathBlows: 110,
    heraldTotalDeaths: 103,
    heraldTotalKills: 635,
    heraldTotalSoloKills: 8,
    heraldHiberniaDeathBlows: 48,
    heraldHiberniaDeaths: 0,
    heraldHiberniaKills: 206,
    heraldHiberniaSoloKills: 4,
  },
  {
    id: 19,
    webId: "s-1NdGVea6Y",
    deathsLastWeek: 0,
    realmPointsLastWeek: 0,
    soloKillsLastWeek: 0,
    totalDeaths: 276,
    totalRealmPoints: 1439689,
    totalSoloKills: 0,
    lastUpdated: new Date("2023-12-24T00:50:59.756Z"),
    characterName: "Divoxeee",
    previousCharacterName: "Unkown",
    className: "Theurgist",
    nameLastUpdated: new Date("2023-12-21T20:25:04.987Z"),
    realm: "Albion",
    heraldAlbionDeathBlows: null,
    heraldAlbionDeaths: null,
    heraldAlbionKills: null,
    heraldAlbionSoloKills: null,
    heraldBountyPoints: 240520,
    heraldCharacterWebId: "s-1NdGVea6Y",
    heraldClassName: "Theurgist",
    heraldGuildName: "Cephina's Angels",
    heraldLevel: 50,
    heraldMasterLevel: "8 Convoker",
    heraldMidgardDeathBlows: 127,
    heraldMidgardDeaths: 0,
    heraldMidgardKills: 1565,
    heraldMidgardSoloKills: 0,
    heraldName: "Divoxeee",
    heraldRace: "Briton",
    heraldRealm: 1,
    heraldRealmPoints: 1439689,
    heraldServerName: "Ywain1",
    heraldTotalDeathBlows: 291,
    heraldTotalDeaths: 276,
    heraldTotalKills: 3777,
    heraldTotalSoloKills: 0,
    heraldHiberniaDeathBlows: 164,
    heraldHiberniaDeaths: 0,
    heraldHiberniaKills: 2212,
    heraldHiberniaSoloKills: 0,
  },
];

const characters = [...charactersSet1, ...charactersSet2];

async function main() {
  console.log("Seeding Users...");
  for (const user of users) {
    await prisma.user.upsert({
      where: { id: user.id },
      update: user,
      create: user,
    });
  }

  console.log("Seeding Characters...");
  for (const character of characters) {
    await prisma.character.upsert({
      where: { id: character.id },
      update: character,
      create: character,
    });
  }

  console.log("Seeding UserCharacters...");
  for (const userChar of userCharacters) {
    await prisma.userCharacter.upsert({
      where: {
        characterId_clerkUserId: {
          characterId: userChar.characterId,
          clerkUserId: userChar.clerkUserId,
        },
      },
      update: userChar,
      create: userChar,
    });
  }

  console.log("Seeding complete!");
}
main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
